# Generated by Django 4.2.5 on 2024-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0005_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
